In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
ds = pd.read_csv("CO2 PPM.csv")
ds

Date  Decimal Date  Interpolated   Trend  Number of Days  Average
0    01-03-1958      1958.208        315.71  314.62              -1   315.71
1    01-04-1958      1958.292        317.45  315.29              -1   317.45
2    01-05-1958      1958.375        317.50  314.71              -1   317.50
3    01-06-1958      1958.458        317.10  314.85              -1   317.10
4    01-07-1958      1958.542        315.86  314.98              -1   315.86
5    01-08-1958      1958.625        314.93  315.94              -1   314.93
6    01-09-1958      1958.708        313.20  315.91              -1   313.20
7    01-10-1958      1958.792        312.66  315.61              -1   312.66
8    01-11-1958      1958.875        313.33  315.31              -1   313.33
9    01-12-1958      1958.958        314.67  315.61              -1   314.67
10   01-01-1959      1959.042        315.62  315.70              -1   315.62
11   01-02-1959      1959.125        316.38  315.88              -1   316.38
12   01-03-1959      1959.208        316.71  315.62              -1   316.71
13   01-04-1959      1959.292        317.72  315.56              -1   317.72
14   01-05-1959      1959.375        318.29  315.50              -1   318.29
15   01-06-1959      1959.458        318.15  315.92              -1   318.15
16   01-07-1959      1959.542        316.54  315.66              -1   316.54
17   01-08-1959      1959.625        314.80  315.81              -1   314.80
18   01-09-1959      1959.708        313.84  316.55              -1   313.84
19   01-10-1959      1959.792        313.26  316.19              -1   313.26
20   01-11-1959      1959.875        314.80  316.78              -1   314.80
21   01-12-1959      1959.958        315.58  316.52              -1   315.58
22   01-01-1960      1960.042        316.43  316.51              -1   316.43
23   01-02-1960      1960.125        316.97  316.47              -1   316.97
24   01-03-1960      1960.208        317.58  316.49              -1   317.58
25   01-04-1960      1960.292        319.02  316.86              -1   319.02
26   01-05-1960      1960.375        320.03  317.24              -1   320.03
27   01-06-1960      1960.458        319.59  317.36              -1   319.59
28   01-07-1960      1960.542        318.18  317.30              -1   318.18
29   01-08-1960      1960.625        315.91  316.92              -1   315.91
..          ...           ...           ...     ...             ...      ...
697  01-04-2016      2016.292        407.45  404.65              25   407.45
698  01-05-2016      2016.375        407.72  404.40              29   407.72
699  01-06-2016      2016.458        406.83  404.53              26   406.83
700  01-07-2016      2016.542        404.41  404.03              28   404.41
701  01-08-2016      2016.625        402.27  404.18              23   402.27
702  01-09-2016      2016.708        401.05  404.56              24   401.05
703  01-10-2016      2016.792        401.59  404.89              29   401.59
704  01-11-2016      2016.875        403.55  405.53              27   403.55
705  01-12-2016      2016.958        404.45  405.11              30   404.45
706  01-01-2017      2017.042        406.17  405.88              26   406.17
707  01-02-2017      2017.125        406.46  405.68              26   406.46
708  01-03-2017      2017.208        407.22  405.73              23   407.22
709  01-04-2017      2017.292        409.04  406.25              25   409.04
710  01-05-2017      2017.375        409.69  406.36              27   409.69
711  01-06-2017      2017.458        408.88  406.58              26   408.88
712  01-07-2017      2017.542        407.12  406.74              28   407.12
713  01-08-2017      2017.625        405.13  407.04              29   405.13
714  01-09-2017      2017.708        403.37  406.88              26   403.37
715  01-10-2017      2017.792        403.63  406.93              27   403.63
716  01-11-2017      2017.875        405.12  407.09              26   405.12
717  01

In [3]:
x = ds.iloc[:,0:5]
x

Date  Decimal Date  Interpolated   Trend  Number of Days
0    01-03-1958      1958.208        315.71  314.62              -1
1    01-04-1958      1958.292        317.45  315.29              -1
2    01-05-1958      1958.375        317.50  314.71              -1
3    01-06-1958      1958.458        317.10  314.85              -1
4    01-07-1958      1958.542        315.86  314.98              -1
5    01-08-1958      1958.625        314.93  315.94              -1
6    01-09-1958      1958.708        313.20  315.91              -1
7    01-10-1958      1958.792        312.66  315.61              -1
8    01-11-1958      1958.875        313.33  315.31              -1
9    01-12-1958      1958.958        314.67  315.61              -1
10   01-01-1959      1959.042        315.62  315.70              -1
11   01-02-1959      1959.125        316.38  315.88              -1
12   01-03-1959      1959.208        316.71  315.62              -1
13   01-04-1959      1959.292        317.72  315.56              -1
14   01-05-1959      1959.375        318.29  315.50              -1
15   01-06-1959      1959.458        318.15  315.92              -1
16   01-07-1959      1959.542        316.54  315.66              -1
17   01-08-1959      1959.625        314.80  315.81              -1
18   01-09-1959      1959.708        313.84  316.55              -1
19   01-10-1959      1959.792        313.26  316.19              -1
20   01-11-1959      1959.875        314.80  316.78              -1
21   01-12-1959      1959.958        315.58  316.52              -1
22   01-01-1960      1960.042        316.43  316.51              -1
23   01-02-1960      1960.125        316.97  316.47              -1
24   01-03-1960      1960.208        317.58  316.49              -1
25   01-04-1960      1960.292        319.02  316.86              -1
26   01-05-1960      1960.375        320.03  317.24              -1
27   01-06-1960      1960.458        319.59  317.36              -1
28   01-07-1960      1960.542        318.18  317.30              -1
29   01-08-1960      1960.625        315.91  316.92              -1
..          ...           ...           ...     ...             ...
697  01-04-2016      2016.292        407.45  404.65              25
698  01-05-2016      2016.375        407.72  404.40              29
699  01-06-2016      2016.458        406.83  404.53              26
700  01-07-2016      2016.542        404.41  404.03              28
701  01-08-2016      2016.625        402.27  404.18              23
702  01-09-2016      2016.708        401.05  404.56              24
703  01-10-2016      2016.792        401.59  404.89              29
704  01-11-2016      2016.875        403.55  405.53              27
705  01-12-2016      2016.958        404.45  405.11              30
706  01-01-2017      2017.042        406.17  405.88              26
707  01-02-2017      2017.125        406.46  405.68              26
708  01-03-2017      2017.208        407.22  405.73              23
709  01-04-2017      2017.292        409.04  406.25              25
710  01-05-2017      2017.375        409.69  406.36              27
711  01-06-2017      2017.458        408.88  406.58              26
712  01-07-2017      2017.542        407.12  406.74              28
713  01-08-2017      2017.625        405.13  407.04              29
714  01-09-2017      2017.708        403.37  406.88              26
715  01-10-2017      2017.792        403.63  406.93              27
716  01-11-2017      2017.875        405.12  407.09              26
717  01-12-2017      2017.958        406.81  407.47              31
718  01-01-2018      2018.042        407.96  407.67              29
719  01-02-2018      2018.125        408.32  407.54              28
720  01-03-2018      2018.208        409.41  407.92              30
721  01-04-2018      2018.292        410.24  407.45              21
722  01-05-2018      2018.375        411.24  407.91              24
723  01-06-2018      2018.458        410.79  408.49              29

In [5]:
x = x.values
y = y.values

In [12]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
le_x = LabelEncoder()
x[:,0] = le_x.fit_transform(x[:,0])
x

array([[120, 1958.2079999999999, 315.71, 314.62, -1],
       [181, 1958.2920000000001, 317.45, 315.29, -1],
       [242, 1958.375, 317.5, 314.71, -1],
       ...,
       [424, 2018.5420000000001, 408.71, 408.32, 27],
       [485, 2018.625, 406.99, 408.9, 30],
       [546, 2018.7079999999999, 405.51, 409.02, 29]], dtype=object)

In [14]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size = 0.8, random_state = 42)

C:\Users\karthikram\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


In [15]:
from sklearn.linear_model import LinearRegression
LinReg = LinearRegression()
LinReg.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [16]:
y_predict = LinReg.predict(x_train)
y_predict

array([326.05095228, 340.91724215, 313.33067518, 394.35929715,
       383.8990339 , 346.52053679, 336.10311205, 328.32446188,
       350.50928051, 325.78993432, 340.29739493, 397.45254215,
       316.9514479 , 323.19968863, 342.36007771, 316.8342847 ,
       355.56027297, 397.53607365, 345.90412932, 373.78438392,
       317.78294837, 353.76547032, 362.2315739 , 393.34576041,
       344.78957012, 364.62125962, 325.23248513, 319.54233731,
       320.80893716, 354.78306679, 378.73854934, 366.84303296,
       344.74556699, 341.02897294, 368.10840235, 396.83540321,
       387.84315822, 313.96251114, 345.15841071, 351.42639512,
       402.53356131, 320.57281471, 321.6265891 , 371.77878223,
       392.53454547, 316.0779201 , 380.09245418, 409.82564644,
       395.2919462 , 349.04899736, 332.69310588, 369.4902584 ,
       386.42491271, 357.88656075, 381.82904227, 352.86636267,
       332.04983053, 340.05973816, 359.37438265, 386.57723488,
       326.58455817, 338.20718735, 334.12153086, 375.82

In [20]:
LinReg.score(x_train,y_train)

0.9986131755816301

In [22]:
input = [[181, 1958.292, 317.45, 315.29, -1]]
ans = LinReg.predict(input)
ans

array([317.71794398])